'of=de' 'and=e' 'a=um' 'to=para' 'in=em' 'is=é' 'you=você' 'that=que' 'it=ele' 'he=ele' 'for=para' 'was=foi' 'on=em' 'are=são' 'as=como' 'with=com' 'his=sua' 'they=eles' 'at=em' 'be=ser' 'this=isto' 'from=de' 'I=Eu' 'have=ter' 'or=ou' 'by=por' 'one=um' 'had=tinha' 'not=não' 'but=mas' 'what=o que' 'all=todos' 'were=foram' 'when=quando' 'we=nós' 'there=lá, ali' 'can=pode' 'an=um' 'your=sua' 'which=que' 'their=sua' 'said=disse' 'if=se' 'do=fazer' 'will=vai' 'each=cada' 'about=sobre' 'how=como' 'up	para cima'
'out' 'fora' 'them' 'eles' 'then' 'então, depois' 'she' 'ela' 'many' 'muitos' 'some' 'alguns' 'so' 'assim' 'these' 'esses' 'would' 'seria' 'other' 'outros' 'into' 'em' 'has' 'tem' 'more' 'mais' 'her' 'sua' 'two' 'dois' 'like' 'como' 'him' 'ele' 'see' 'veja' 'time' 'tempo' 'could' 'poderia' 'no' 'não' 'make' 'fazer' 'than' 'que' 'first' 'primeiro' 'been' 'foi' 'its' 'sua' 'who' 'que' 'now' 'agora' 'people' 'pessoas' 'my' 'a minha' 'made' 'feito' 'over' 'superior, mais' 'did' 'fez' 'down' 'baixo' 'only' 'apenas' 'way' 'forma' 'find' 'encontrar' 'use' 'uso' 'may' 'pode' 'water' 'água' 'long' 'tempo' 'little' 'pouco' 'very' 'muito' 'after' 'depois' 'words' 'palavras' 'called' 'chamada' 'just' 'apenas' 'where' 'onde' 'most' 'mais' 'know' 'saber' 
'get' 'obter' 'through' 'através' 'back' 'volta' 'much' 'muito' 'before' 'antes' 'go' 'ir' 'good' 'boa' 'new' 'novo' 'write' 'escrever' 'our' 'nossa' 'used' 'usados' 'me' 'me, mim' 'man' 'homem' 'too' 'também' 'any' 'qualquer' 'day' 'dia' 'same' 'mesmo' 'right' 'direito' 'look' 'olhar' 'think' 'pensar' 'also' 'também' 'around' 'em torno de' 'another' 'outro' 'came' 'veio' 'come' 'vem' 'work' 'trabalho' 'three' 'três' 'word' 'palavra' 'must' 'deve' 'because' 'porque' 'does' 'faz part' 'parte even' 'mesmo place' 'lugar' 'well' 'bem' 'such' 'tais' 'here' 'aqui' 'take' 'ter' 'why' 'por que' 'things' 'coisas' 'help' 'ajuda' 'put' 'colocar' 'years' 'anos' 'different' 'diferente' 'away' 'distância' 'again' 'novamente' 'off' 'fora' 'went' 'foi' 'old' 'velho, antigo' 'number' 'número'






