modulo1=('the' 'o,a,os,as' 'of' 'de' 'and' 'e' 'a' 'um' 'to' 'para' 'in' 'em' 'is' 'é' 'you' 'você' 'that' 'que' 'it' 'ele' 'he' 'ele' 'for' 'para' 'was' 'foi' 'on' 'em' 'are' 'são' 'as' 'como' 'with' 'com' 'his' 'sua' 'they' 'eles' 'at' 'em' 'be' 'ser' 'this' 'isto' 'from' 'de' 'i' 'eu' 'have' 'ter' 'or' 'ou' 'by' 'por' 'one' 'um' 'had' 'tinha' 'not' 'não' 'but' 'mas' 'what' 'o que' 'all' 'todos' 'were' 'foram' 'when' 'quando' 'we' 'nós' 'there' 'lá,ali' 'can' 'pode' 'an' 'um' 'your' 'sua' 'which' 'que' 'their' 'sua' 'said' 'disse' 'if' 'se' 'do' 'fazer' 'will' 'vai' 'each' 'cada' 'about' 'sobre' 'how' 'como' 'up' 'para cima')
modulo2=('out' 'fora' 'them' 'eles' 'then' 'então, depois' 'she' 'ela' 'many' 'muitos' 'some' 'alguns' 'so' 'assim' 'these' 'esses' 'would' 'seria' 'other' 'outros' 'into' 'em' 'has' 'tem' 'more' 'mais' 'her' 'sua' 'two' 'dois' 'like' 'como' 'him' 'ele' 'see' 'veja' 'time' 'tempo' 'could' 'poderia' 'no' 'não' 'make' 'fazer' 'than' 'que' 'first' 'primeiro' 'been' 'foi' 'its' 'sua' 'who' 'que' 'now' 'agora' 'people' 'pessoas' 'my' 'a minha' 'made' 'feito' 'over' 'superior, mais' 'did' 'fez' 'down' 'baixo' 'only' 'apenas' 'way' 'forma' 'find' 'encontrar' 'use' 'uso' 'may' 'pode' 'water' 'água' 'long' 'tempo' 'little' 'pouco' 'very' 'muito' 'after' 'depois' 'words' 'palavras' 'called' 'chamada' 'just' 'apenas' 'where' 'onde' 'most' 'mais' 'know' 'saber' )
modulo=()
modulo=()
modulo=()
modulo=()
modulo=()
modulo=()
modulo=()
modulo=()

